version: "3.2"
services:
    db:
        image: postgres
        volumes:
            - my_app_db_django:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: test
            POSTGRES_DB: test
            POSTGRES_PASSWORD: test
        ports:
            - 5439:5432
        networks:
            - net-my_app-db-django
    app:
        build:
            context: ./app/backend/
            dockerfile: Dockerfile
        image: app
        volumes:
            - ./app/backend:/app/backend
        networks:
            - net-my_app-db-django
            - my_app-app-django-net
        depends_on:
            - db
    frontend:
        build:
            context: ./app/frontend/
            dockerfile: Dockerfile
        volumes:
            - ./app/frontend:/app/frontend
        ports:
            - 3000:3000
        depends_on:
            - app
        networks:
            - my_app-app-django-net
    gateway:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - app
        networks:
            - my_app-app-django-net
        ports:
            - 8000:8000
volumes:
    my_app_db_django:

networks:
    net-my_app-db-django:
    my_app-app-django-net:


